
#ifndef _PTH_FRAMEWORK_ENGIEN_PUBLIC_EMGINE_ENGINEENUM_H
#define _PTH_FRAMEWORK_ENGIEN_PUBLIC_EMGINE_ENGINEENUM_H

namespace Engine {

	 enum TEXTYPE : unsigned short
	{
		TextureType_NONE = 0,
		TextureType_DIFFUSE = 1,
		TextureType_SPECULAR = 2,
		TextureType_AMBIENT = 3,
		TextureType_EMISSIVE = 4,
		TextureType_HEIGHT = 5,
		TextureType_NORMALS = 6,
		TextureType_SHINNESS = 7,
		TextureType_OPACITY = 8,
		TextureType_DISPLACEMENT = 9,
		TextureType_LIGHTMAP = 10,
		TextureType_REFLECTION = 11,
		TextureType_BASE_COLOR = 12,
		TextureType_NORMAL_CAMERA = 13,
		TextureType_EIMISSION_COLOR = 14,
		TextureType_METALNESS = 15,
		TextureType_DIFFUSE_ROUGHTNESS = 16,
		TextureType_AMBIENT_OCCLUSION = 17,
		TextureType_UNKNOWN = 18
	};
	 
	 typedef enum ERenderID : _ubyte
	 {
		 // 첫 번째 그려질 것
		 RI_NONALPHA_PRIORITY, RI_SHADOW, RI_NONALPHA_FIRST , RI_NONALPHA_LAST, RI_NONALPHA_MIDDLE, RI_ALPHA ,RI_DISTORTION, RI_NOLIGHT, RI_3DUI, RI_2DUI,
		 RI_END
	 }RENDERID;
	 typedef enum EDebugRederID : _ubyte
	 {
		 DEBUG_RI_MAP, DEBUG_RI_PLAYER, DEBUG_RI_ETC, DEBUG_RI_END
	 }DEBUGRENDERID;

	 // Render Object Type 
	 enum class GRAPHICRENDEROBJECT_TYPE : unsigned short  { COMMON,  LIGHT, ALPHA, NONALPHA, RENDEROBJECT_END };

	 enum  class ROOT_REGISTER_TYPE : unsigned short
	 {
		 COMMON, GRAPHI_LIGHT,
		 // Compute는 따로 정의
		 COMPUTE_COMMON, ROOT_REGISTER_END
	 };

	 enum ROOT_REGISTER_SPACE : unsigned short
	 {
		 ROOTREGISTER_SPACE_COMMON = 0,
		 ROOTREGISTER_SPACE_LIGHT = 1,
	 };

	 enum class GRAPHICISCONTROLTYPE : unsigned char
	 {
		 GRAPHICS, COMPUTE, TYPE_END
	 };

	 // Light
	 enum class  LIGHTTYPE { TYPE_DIRECTIONAL, TYPE_POINT, TYPE_SPOT, TYPE_FLASHLIGHT, LIGHT_END };

	enum  SHADERMAININFO : unsigned short  {
		VS_MAIN = 0,
		HS_MAIN,
		DS_MAIN,
		GS_MAIN,
		PS_MAIN,
		CS_MAIN,
	};

	enum class DESCRIPTOR_TYPE : unsigned short {
		SRV, RTV, DSV, UAV, TYPE_END
	};

	enum class RASTERIZER_TYPE : unsigned short {
		CULL_NONE,
		CULL_FRONT,
		CULL_BACK,
		WIREFRAME,
	};

	enum class DEPTH_STENCIL_TYPE : unsigned short {
		LESS,
		LESS_EQUAL,
		GREATER,
		GREATER_EQUAL,
		NO_DEPTH_TEST, // 깊이 테스트(X) + 깊이 기록(O)
		NO_DEPTH_TEST_NO_WRITE, // 깊이 테스트(X) + 깊이 기록(X)
		LESS_NO_WRITE, // 깊이 테스트(O) + 깊이 기록(X)
	};

	enum class BLEND_TYPE : unsigned short {
		DEFAULT,
		ALPHA_BLEND,
		ONE_TO_ONE_BLEND,
		ADD_BLEND,
		BLEND_END,
	};


	enum class CBV_REGISTER : unsigned short {
		B0, B1, B2, B3, B4, B5, B6, B7, B8, B9, B10, B11, B12, B13, B14, CBV_END

		, VIEWPROJ = B0
		, TRANSFORM = B2
		, ANIMMODEL = B11
		, BONEMATRIX = B12
		, PREVBONEMATRIX = B13
		, STATICLIGHT= B0
		, LIGHTCONTROL = B1
		, NORMALCUBEPARAM = B13
		, ALLPARTICLEBUFFER = B14
		, GROBALDATA = B1
		, WATERPARAM = B14
		, SOCKETMATRIX = B13
		,ANIMATEPARTICLEPARAM = B13
		,
	};

	enum class SRV_REGISTER : unsigned short {
		T0 = static_cast<unsigned int>(CBV_REGISTER::CBV_END),
		T1,
		T2,
		T3,
		T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14,

		SRV_END
	};

	enum class UAV_REGISTER : unsigned short {
		U0 = static_cast<unsigned int>(SRV_REGISTER::SRV_END),
		U1, 
		U2, U3, U4, U5, U6, U7, U8, U9, U10, U11, U12, U13, U14,

		UAV_END,

		ANIMTEXTURE = U0,

		PARTICLEWRITEDATA = U0, 
		SHRAEDDATA = U1,

	};

	enum class TEXTURECREATETYPE : unsigned short {
		TEX2D, TEXCUBE, TEXDIMMESION, TEXARRAY, TEX_END
	};

	enum class RTGROUPID {
		DEFAULT = 0,
		LIGHTSHADE_DEFFERED,
		NONALPHA_DEFFERED ,
		ALPHA_DEFFERED, 
		UI2D_DEFFERED, 
		BLEND_DEFFERED ,

		ENDGROUP
	};

	enum class RTOBJID {
		SWAPCHAIN1 = 0,
		SWAPCHAIN2 = 1,
		SWAPCHAIN3 = 2,

		LIGHTSHADE_AMBIENT_DEFFERED,
		LIGHTSHADE_SHADE_DEFFERED,
		LIGHTSHADE_SPECULAR_DEFFERED,

		NONALPHA_DIFFUSE_DEFFERED,
		NONALPHA_NOMRAL_DEFFERED,
		NONALPHA_DEPTH_DEFFERED,
		NONALPHA_POSITION_DEFFERED,

		ALPHA_DIFFUSE_DEFFERED,
		ALPHA_GLOW_DEFFERED,
		ALPHA_BLUR_DEFFERED, 

		BLEND_SCREEN_DEFFERED,

		UI2D_SCREEN_DEFFERED,

		RTOBJ_END,

		RTGROUP_LIGHTSHADE_DEFFERED_CNT = 3,
		RTGROUP_NONALPHA_DEFFERED_CNT = 4,
		RTGROUP_ALPHA_DEFFERED_CNT = 3,
		RTGROUP_BLEND_DEFFERED_CNT = 1,
		
	};

	enum class CLONETYPE : unsigned char {
		CLONE_STATIC, CLONE_ONCE,  CLONE_REMAINVALUE, CLONE_END
	};

	enum class BACKINGTYPE : unsigned char {
		STATIC, DYNAMIC, NON, BACKING_END
	};

	enum class USECOLLISIONTYPE : unsigned char {
		 ACTIVE, DISABLE, USECOLL_END
	};

	enum  GROBAL_CBUFFERTYPE : _ubyte
	{
		GROBAL_VIEWPROJ, 
		GROBAL_GROBALDATA,
		GROBAl_LIGHTSTATIC, 
		GROBAL_BUFFER_END
	};

	enum PREALLOCATED_CBUFFERTYPE :_ubyte
	{
		PREALLOCATED_TRANSFORM,
		PREALLOCATED_BUFFER_END
	};

	enum class PRESSTYPE : _ubyte {
		DOWN, ING, UP, EMPTY
	};

	enum class CAMERATYPE
	{
		MAIN,  DEFFERED,  SHADOWLIGHT, OTEHR,
	};

	enum class VIBUFFERTYPE
	{
		GENERIC, NORMAL, BUFFEREND
	};

	enum DIMOUSEMOVE { DIMM_X, DIMM_Y, DIMM_WHEEL, DIMM_END };
	enum DIMOUSEBUTTON { DIMB_L, DIMB_R, DIMB_WHEEL, DIMB_END };
	enum class CURSOR_LOCKMODE { LOCKED, CONFINED, NONE, EMPTY };

	enum VALUES
	{
		MAIN_CAMERA_ID = static_cast<_uint>(CAMERATYPE::MAIN),
		DEFFERED_CAMERA_ID = static_cast<_uint>(CAMERATYPE::DEFFERED),
		SHADOWLIGHT_CAMERA_ID = static_cast<_uint>(CAMERATYPE::SHADOWLIGHT),
		SWAP_CHAIN_END = 3,
		GRAPHICS_CONSTANT_BUFFER_VALUE = 2,
		COMPUTE_CONSTANT_BUFFER_VALUE = 0,
		LIGHT_CONSTANT_BUFFER_VALUE = 1,
		CBV_REGISTER_END = CBV_REGISTER::CBV_END,
		SRV_REGISTER_END = 15,
		UAV_REGISTER_END = 15,
		REGISTER_CNT = (CBV_REGISTER_END + SRV_REGISTER_END + UAV_REGISTER_END),

		LIGHT_CBV_REGISTER_END = 3,
		LIGHT_SRV_REGISTER_END = 5,

		SCENE_STATIC_VALUE = 0,



		// Clone Max Size
		CLONE_MAX_SIZE = static_cast<unsigned int>(CLONETYPE::CLONE_END),
		RTTARGET_LIGHTSHADE_DEFFERED_MAXNUM = static_cast<unsigned int>(RTOBJID::RTGROUP_LIGHTSHADE_DEFFERED_CNT),
		RTTARGET_NONALPHA_DEFFERED_MAXNUM = static_cast<unsigned int>(RTOBJID::RTGROUP_NONALPHA_DEFFERED_CNT),
		RTTARGET_ALPHA_DEFFERED_MAX_NUM = static_cast<unsigned int>(RTOBJID::RTGROUP_ALPHA_DEFFERED_CNT),
		RTTARGET_BLEND_DEFFERED_MAXNUM = static_cast<unsigned int>(RTOBJID::RTGROUP_BLEND_DEFFERED_CNT),

		MAX_KEYSIZE = 256,
		MAX_FRUSTOMSIZE = 8,

		MAX_CAM_SIZE = 10,
		MAX_BONE_SIZE = 512,
		MAX_THREAD_CNT = 16,
		MAX_THREAD_COMMAND_CNT = 18,
		MAX_RENDERPASS_CNT = 2,
		MAX_SCREEN_RENDERING_CNT = 10,

		MAX_ROOT_REGISTER_CNT = static_cast<unsigned int>(ROOT_REGISTER_TYPE::ROOT_REGISTER_END),
		MAX_RENDEROBJECT_CNT = static_cast<unsigned int>(GRAPHICRENDEROBJECT_TYPE::RENDEROBJECT_END),

		COMMON_GRAPHICS_REGISTER_CNT = CBV_REGISTER_END + SRV_REGISTER_END,
		LIGHT_GRAPHICS_REGISTER_CNT = LIGHT_CBV_REGISTER_END + LIGHT_SRV_REGISTER_END,

	};
}

#endif // _PTH_FRAMEWORK_ENGIEN_PUBLIC_EMGINE_ENGINEENUM_H